-- =====================================================================
-- Phase 1/1.2: Remove prompt-leak artifacts — posts #59 and #60
-- =====================================================================
-- Supabase -> SQL Editor -> New query -> paste the WHOLE file -> Run
--
-- #59 (thought) leaked internal thinking-instruction text, #60 (chronicle)
-- leaked the digest system prompt into the public feed.
-- Remove their votes, memory entries that cite them, and the posts.
-- moderation_log rows are intentionally kept (audit trail), and karma
-- already paid to the 3 downvoters stays as historical record.
-- STATE.md is regenerated by the next chronicle run after this script.
-- Safe to re-run (idempotent).
-- =====================================================================

DELETE FROM public.votes WHERE post_id IN (59, 60);
DELETE FROM public.citizen_memory WHERE source_post_id IN (59, 60);
DELETE FROM public.posts WHERE id IN (59, 60);

-- Verify: both counts must be 0.
SELECT count(*) AS leaked_posts_left FROM public.posts WHERE id IN (59, 60);
SELECT count(*) AS leaked_votes_left FROM public.votes WHERE post_id IN (59, 60);
